### ISSUE TITLE
Special characters cause a crash parsing the file.

### ISSUE THREAD

**Issue by bcerrato** [I8C/sonar-flow-plugin#13]
Our flow XML is UTF-8 encoded, but we have a rule that checks for special characters to prevent them from flowing into our services. That ends up with a Mapset Value entry that looks like the following:

```
<Values version="2.0">
  <value name="xml">Æ</value>
  <record name="type" javaclass="com.wm.util.Values">
    <value name="node_type">unknown</value>
    <value name="is_public">false</value>
    <value name="field_name">searchString</value>
    <value name="field_type">string</value>
    <value name="field_dim">0</value>
    <value name="nillable">true</value>
    <value name="form_qualified">false</value>
    <value name="is_global">false</value>
  </record>
</Values>
```

This causes the plugin to crash with:
```
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Inval
id byte 2 of 2-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF
8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader
.java:372)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEnti
tyScanner.java:1896)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.peekChar(XML
EntityScanner.java:507)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2716)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next
(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:643)
        at be.i8c.codequality.sonar.plugins.sag.webmethods.flow.sslr.channels.Sa
xChannel.consume(SaxChannel.java:57)
        at be.i8c.codequality.sonar.plugins.sag.webmethods.flow.sslr.channels.Sa
xChannel.consume(SaxChannel.java:39)
        at org.sonar.sslr.channel.ChannelDispatcher.consume(ChannelDispatcher.ja
va:42)
        at com.sonar.sslr.impl.Lexer.lex(Lexer.java:127)
        at com.sonar.sslr.impl.Lexer.lex(Lexer.java:96)
        at com.sonar.sslr.impl.Lexer.lex(Lexer.java:82)
        at com.sonar.sslr.impl.Parser.parse(Parser.java:68)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
        at be.i8c.codequality.sonar.plugins.sag.webmethods.flow.rule.FlowSquidSe
nsor.analyse(FlowSquidSensor.java:123)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecuto
r.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java
:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseE
xecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanCon
tainer.java:182)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:127)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer
.java:247)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectSc
anContainer.java:242)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanC
ontainer.java:232)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:127)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:
86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer
.java:127)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContain
er.java:115)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.exec
ute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(Iso
latedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner
.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScann
er.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by dewanst** [comment]
Hi Brent

I tried pasting your snippet with the special char in one of our flow.xml unit tests and it succeeds without an error. Could you share the complete flow.xml, so we can try and replicate your problem?

**Comment by bcerrato** [comment]
Flow.xml and sonar project used attached.
[flow.zip](https://github.com/I8C/sonar-flow-plugin/files/799378/flow.zip)
[sonar-project.zip](https://github.com/I8C/sonar-flow-plugin/files/799379/sonar-project.zip)

**Comment by dewanst** [comment]
Hi Brent

I can scan your file without an error. Looking at your error:
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 2-byte UTF-8 sequence.
It seems your file is not UTF-8 encoded (although the file you shared is indeed UTF-8). I would suggest you check if the file that is being read by the scanner isn't in another encoding.

If I change the file to ANSI, I get the same error you have.

**Comment by bcerrato** [comment]
I sent the file directly from disk that's generating the error. In the mean time, I altered the code to scan in a loop rather than all of them at once. This allows me to catch the exception and skip the file rather than die on the whole scan.

**Comment by Samuelvdc** [comment]
Could you share your code changes? So we can see if we can merge it.

**Comment by bcerrato** [comment]
Attached changes. I can't commit them to an issue branch, but there's only really one file changed.


[FlowSquidSensor.java.txt](https://github.com/I8C/sonar-flow-plugin/files/858312/FlowSquidSensor.java.txt)

**Comment by bcerrato** [comment]
Yes. Sounds perfect.

**Comment by AgentW4C** [comment]
Is this issue really fixed in the recent release? I think I'm encountering similar issue.

**Comment by bcerrato** [comment]
You can enable the option to skip failed files... but that particular file is just skipped.
