### ISSUE TITLE
#3 Nullpointer exception when no dependencies

### ISSUE THREAD

**Issue by dewanst** [I8C/sonar-flow-plugin#3]
java.lang.NullPointerException
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
        at be.i8c.codequality.sonar.plugins.sag.webmethods.flow.rule.FlowSquidSensor.setTopLevelServices(FlowSquidSensor.java:150)
        at be.i8c.codequality.sonar.plugins.sag.webmethods.flow.rule.FlowSquidSensor.analyse(FlowSquidSensor.java:122)

When running on an empty service (no dependencies)

**Comment by dewanst** [comment]
Fixed in code
